baseurl = "https://yuanj.top"
title = "JiaoYuan's blog"
languageCode = "en-us"
pagination = { pagerSize = 10 }
theme = ["cloud"]

[Params]
  post_meta = ["date"]
  mainSections = ["p"]

[Params.topbar]
  subtitle = "思绪来得快去得也快，偶尔会在这里停留"

[Params.sidebar]
  home = "right"
  widgets = ["misc", "search", "recent", "archives"]

[Params.widgets]
  recent_num = 15
  [[Params.widgets.misc.custom]]
  title = "README"
  url = "/readme"
  [[Params.widgets.misc.custom]]
  title = "Friends"
  url = "/friends"
  [[Params.widgets.misc.custom]]
  title = "Lumen"
  url = "/lumen"
  [[Params.widgets.misc.custom]]
  title = "feed"
  url = "/index.xml"

[Params.widgets.search]
  title = "search"
  placeholder = "search..."

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true